//! Compiles the normalised image pool into the binary (D29).
//!
//! The alternative — and what the deploy used to do — was to copy `pool/normalised/` next to the
//! client bundle and let the static-file layer serve it. That works, and it has one failure mode
//! worth removing: the images and the manifest are shipped separately, so a deploy that updates
//! one and not the other produces a service that starts cleanly, draws trials normally, and shows
//! eight broken images. Compiling them in makes that state unrepresentable — there is one artefact,
//! and a manifest naming an image the artefact does not carry is refused at startup.
//!
//! It costs a large binary and a rebuild for every pool version. Both are the point: a pool version
//! is immutable once published (D5), so "the images changed" and "this is a different build" ought
//! to be the same statement.
//!
//! The directory is a build *input* that is not in the repository — `pool/normalised/` is
//! gitignored, because it is itself generated, by `poolctl import` from the sources named in
//! `pool/images.toml`. A fresh clone therefore has no images and builds an empty pool rather than
//! failing: the tests do not need them, and the startup check is where a real deployment finds out.

use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let dir = pool_dir();
    println!("cargo::rerun-if-env-changed=VRILTRAINER_POOL_IMAGES");
    println!("cargo::rerun-if-changed={}", dir.display());

    let mut images = read_dir(&dir);
    // Sorted so the generated file is byte-identical for the same inputs, and so the lookup can
    // binary-search rather than scan 189 entries per request.
    images.sort();

    if images.is_empty() {
        println!(
            "cargo::warning=no images in {} — this build serves no pool. \
             Run `cargo run --bin poolctl -- import` first.",
            dir.display()
        );
    }

    let mut out = String::from(
        "// Generated by build.rs. The pool, as bytes in the binary.\n\
         pub(super) static IMAGES: &[(&str, &[u8])] = &[\n",
    );
    for (id, path) in &images {
        // `include_bytes!` and not a runtime read: the point of the exercise is that the bytes are
        // in the artefact and cannot be missing from it.
        out.push_str(&format!(
            "    ({id:?}, include_bytes!({:?})),\n",
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let generated = PathBuf::from(env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("pool.rs");
    fs::write(&generated, out).expect("the generated pool table is writable");
}

/// Where the normalised images live: the override, or `pool/normalised` beside the workspace.
fn pool_dir() -> PathBuf {
    if let Ok(dir) = env::var("VRILTRAINER_POOL_IMAGES") {
        return PathBuf::from(dir);
    }
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    manifest
        .parent()
        .expect("the server crate sits inside the workspace")
        .join("pool")
        .join("normalised")
}

/// Every `img_*.png` in `dir`, as `(id, absolute path)`.
///
/// The identifier is the file *stem*, which is not a convention this reads off a name it does not
/// control: `poolctl` writes each file as `<id>.png` and the id is the hash of the bytes inside it.
/// Anything else in the directory is ignored rather than guessed at.
fn read_dir(dir: &Path) -> Vec<(String, PathBuf)> {
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    entries
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "png"))
        .filter_map(|p| {
            let id = p.file_stem()?.to_str()?.to_owned();
            id.starts_with("img_").then_some((id, p))
        })
        .collect()
}
